Revert "Use logging instead of printstacktrace. Remove unnecessary instance object." breaks build
This reverts commit 25dab1d218aab9f15bc031fd4dda184f61c594ce.

Breaks build with error:

packages/apps/VoicePlus/src/org/cyanogenmod/voiceplus/VoicePlusService.java:551: cannot find symbol

Change-Id: I8404241def5a3b9f23556b080c73161d79e117fb